#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^pd-int$ --format={{.Name}})" ]; then
  echo "Creating pd-int Docker network"
  docker network create pd-int
fi


set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose down

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $@
